name: avisai4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  provider: ^6.1.4
  sqflite: ^2.4.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  path: ^1.9.0
  http: ^1.3.0
  connectivity_plus: ^6.1.3
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  permission_handler: ^12.0.0+1
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  url_launcher: ^6.3.1
  # google_maps_flutter: ^2.10.1
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  mockito: ^5.4.4
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/onboarding_city.png'
    - 'assets/images/onboarding_report.png'
    - 'assets/images/onboarding_welcome.png'